openapi: 3.2.0
info:
  title: CloudTalk Other API
  description: '# Introduction

    Welcome to CloudTalk API reference!'
  contact:
    name: CloudTalk API Support
    url: https://www.cloudtalk.io/contact
  version: '1.7'
  x-logo:
    url: https://my.cloudtalk.io/img/logo-cloudtalk-color.png
servers:
- url: https://my.cloudtalk.io/api
tags:
- name: Other
  description: All other helper endpoints.
paths:
  /countries/index.json:
    get:
      tags:
      - Other
      summary: List countries
      responses:
        '200':
          description: All countries
          content:
            application/json:
              schema:
                type: object
                properties:
                  responseData:
                    type: array
                    items:
                      type: object
                      properties:
                        Country:
                          $ref: '#/components/schemas/Country'
              example:
                responseData:
                - Country:
                    id: '61'
                    name: Denmark
                    country_code: DK
                    iso3: DNK
                    calling_code: '45'
                - Country:
                    id: '235'
                    name: United Kingdom
                    country_code: GB
                    iso3: GBR
                    calling_code: '44'
      operationId: getCountriesIndexJson
      x-operation-id-source: derived
  /blacklist/index.json:
    get:
      tags:
      - Other
      summary: List blacklist
      description: List blacklisted numbers.
      parameters:
      - name: id
        in: query
        description: Filter by ID
        schema:
          type: integer
      - name: country_code
        in: query
        description: Filter by country calling code
        schema:
          type: integer
      - name: type
        in: query
        description: Filter by type
        schema:
          type: string
          enum:
          - all
          - incoming
          - outgoing
      - name: public_number
        in: query
        description: Filter by number
        schema:
          type: string
      - name: limit
        in: query
        description: Max. number of items in response data.
        schema:
          maximum: 1000
          minimum: 1
          type: integer
      - name: page
        in: query
        description: Number of page to return.
        schema:
          minimum: 1
          type: integer
      responses:
        '200':
          description: Blacklist data
          content:
            application/json:
              schema:
                type: object
                properties:
                  itemsCount:
                    $ref: '#/components/schemas/PaginationData/properties/itemsCount'
                  pageCount:
                    $ref: '#/components/schemas/PaginationData/properties/pageCount'
                  pageNumber:
                    $ref: '#/components/schemas/PaginationData/properties/pageNumber'
                  limit:
                    $ref: '#/components/schemas/PaginationData/properties/limit'
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        Blacklist:
                          $ref: '#/components/schemas/Blacklist'
              example:
                responseData:
                  itemsCount: 2
                  pageCount: 1
                  pageNumber: 1
                  limit: 2
                  data:
                  - Blacklist:
                      id: '123'
                      type: all
                      public_number: 442012345678
                  - Blacklist:
                      id: '456'
                      type: incoming
                      public_number: 442012345679
      operationId: getBlacklistIndexJson
      x-operation-id-source: derived
  /blacklist/add.json:
    put:
      tags:
      - Other
      summary: Add number to blacklist
      description: Add number to blacklist.
      requestBody:
        content:
          application/json:
            schema:
              required:
              - public_number
              - type
              type: object
              properties:
                type:
                  $ref: '#/components/schemas/Blacklist/properties/type'
                public_number:
                  $ref: '#/components/schemas/Blacklist/properties/public_number'
        required: true
      responses:
        '201':
          description: No error
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    $ref: '#/components/schemas/StatusCode/properties/status'
                  data:
                    type: object
                    properties:
                      id:
                        $ref: '#/components/schemas/Blacklist/properties/id'
              example:
                responseData:
                  status: 201
                  data:
                    id: '12345'
        '406':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorInvalidData'
              example:
                responseData:
                  status: 406
                  message: Invalid input data.
                  data:
                    public_number:
                    - Please supply only valid numbers. Number +441234 is not valid.
        '500':
          description: Something went wrong
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorData'
              example:
                responseData:
                  status: 500
                  message: Something went wrong.
      x-codegen-request-body-name: body
      operationId: putBlacklistAddJson
      x-operation-id-source: derived
  /blacklist/edit/{id}.json:
    post:
      tags:
      - Other
      summary: Edit number on blacklist
      description: Edit blacklisted number.
      parameters:
      - name: id
        in: path
        description: ID to edit
        required: true
        schema:
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              required:
              - public_number
              - type
              type: object
              properties:
                type:
                  $ref: '#/components/schemas/Blacklist/properties/type'
                public_number:
                  $ref: '#/components/schemas/Blacklist/properties/public_number'
        required: true
      responses:
        '200':
          description: No error
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    $ref: '#/components/schemas/StatusCode/properties/status'
              example:
                responseData:
                  status: 200
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorData'
              example:
                responseData:
                  status: 404
                  message: Not found.
        '406':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorInvalidData'
              example:
                responseData:
                  status: 406
                  message: Invalid input data.
                  data:
                    public_number:
                    - Please supply only valid numbers. Number +441234 is not valid.
        '500':
          description: Something went wrong
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorData'
              example:
                responseData:
                  status: 500
                  message: Something went wrong.
      x-codegen-request-body-name: body
      operationId: postBlacklistEdit{id}Json
      x-operation-id-source: derived
  /blacklist/delete/{id}.json:
    delete:
      tags:
      - Other
      summary: Delete number from blacklist
      description: Delete the number from blacklist.
      parameters:
      - name: id
        in: path
        description: ID to delete
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: No error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessGeneralData'
              example:
                responseData:
                  status: 200
        '404':
          description: Blacklist not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorData'
              example:
                responseData:
                  status: 404
                  message: Not found.
        '500':
          description: Something went wrong
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorData'
              example:
                responseData:
                  status: 500
                  message: Something went wrong.
      operationId: deleteBlacklistDelete{id}Json
      x-operation-id-source: derived
components:
  schemas:
    PaginationData:
      type: object
      properties:
        itemsCount:
          type: integer
          description: number of resources in the response
          format: int64
        pageCount:
          type: integer
          description: number of pages found
          format: int64
        pageNumber:
          type: integer
          description: current page in the response
          format: int64
        limit:
          type: integer
          description: number of objects sent per page
          format: int64
      description: Call data
    SuccessGeneralData:
      type: object
      properties:
        status:
          type: string
          description: Status code
    ErrorData:
      type: object
      properties:
        status:
          type: string
          description: Status code
        message:
          type: string
          description: The error message
    StatusCode:
      type: object
      properties:
        status:
          type: string
          description: Status code
    Blacklist:
      type: object
      properties:
        id:
          type: integer
          description: Blacklist ID
        type:
          type: string
          description: Type of calls
          enum:
          - all
          - incoming
          - outgoing
        public_number:
          type: string
          description: Blacklisted number in E.164 format
        created:
          type: string
          description: Created date and time
          format: date-time
        modified:
          type: string
          description: Last modified date and time
          format: date-time
      description: Blacklist data
    ErrorInvalidData:
      type: object
      properties:
        status:
          type: string
          description: Status code
        message:
          type: string
          description: The error message
        data:
          type: object
          properties: {}
          description: More data explaining the error
    Country:
      type: object
      properties:
        id:
          type: integer
          description: Country ID
        name:
          type: string
          description: Name
        country_code:
          type: string
          description: Country code by ISO_3166-1 Alpha-2
        iso3:
          type: string
          description: Country code by ISO_3166-1 Alpha-3
        calling_code:
          type: string
          description: Country calling code
      description: Country data
