openapi: 3.2.0
info:
  title: CloudTalk Tags API
  description: '# Introduction

    Welcome to CloudTalk API reference!'
  contact:
    name: CloudTalk API Support
    url: https://www.cloudtalk.io/contact
  version: '1.7'
  x-logo:
    url: https://my.cloudtalk.io/img/logo-cloudtalk-color.png
servers:
- url: https://my.cloudtalk.io/api
tags:
- name: Tags
  description: All data you can get about your tags.
paths:
  /tags/index.json:
    get:
      tags:
      - Tags
      summary: List tags
      parameters:
      - name: id
        in: query
        description: Filter by tag ID
        schema:
          type: integer
      - name: limit
        in: query
        description: Max. number of items in response data.
        schema:
          maximum: 1000
          minimum: 1
          type: integer
      - name: page
        in: query
        description: Number of page to return.
        schema:
          minimum: 1
          type: integer
      responses:
        '200':
          description: Tags data
          content:
            application/json:
              schema:
                type: object
                properties:
                  itemsCount:
                    $ref: '#/components/schemas/PaginationData/properties/itemsCount'
                  pageCount:
                    $ref: '#/components/schemas/PaginationData/properties/pageCount'
                  pageNumber:
                    $ref: '#/components/schemas/PaginationData/properties/pageNumber'
                  limit:
                    $ref: '#/components/schemas/PaginationData/properties/limit'
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          description: Tag ID
                        name:
                          type: string
                          description: Tag name
              example:
                responseData:
                  itemsCount: 3
                  pageCount: 1
                  pageNumber: 1
                  limit: 3
                  data:
                  - Tag:
                      id: '99'
                      name: Tag
      operationId: getTagsIndexJson
      x-operation-id-source: derived
  /tags/add.json:
    put:
      tags:
      - Tags
      summary: Add a tag
      requestBody:
        content:
          application/json:
            schema:
              required:
              - name
              type: object
              properties:
                name:
                  type: string
                  description: Tag name
        required: true
      responses:
        '201':
          description: No error
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    $ref: '#/components/schemas/StatusCode/properties/status'
                  data:
                    type: object
                    properties:
                      name:
                        type: string
                        description: Tag name
              example:
                responseData:
                  status: 201
                  data:
                    id: '12345'
        '406':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorInvalidData'
              example:
                responseData:
                  status: 406
                  message: Invalid input data.
                  data:
                    name:
                    - Tag has already been used. Please select different one.
        '500':
          description: Something went wrong
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorData'
              example:
                responseData:
                  status: 500
                  message: Something went wrong.
      x-codegen-request-body-name: body
      operationId: putTagsAddJson
      x-operation-id-source: derived
  /tags/edit/{id}.json:
    post:
      tags:
      - Tags
      summary: Edit a tag
      parameters:
      - name: id
        in: path
        description: Tag ID to edit
        required: true
        schema:
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              required:
              - name
              type: object
              properties:
                name:
                  type: string
                  description: Tag name
        required: true
      responses:
        '200':
          description: No error
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    $ref: '#/components/schemas/StatusCode/properties/status'
              example:
                responseData:
                  status: 200
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorData'
              example:
                responseData:
                  status: 404
                  message: Not found.
        '406':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorInvalidData'
              example:
                responseData:
                  status: 406
                  message: Invalid input data.
                  data:
                    name:
                    - Tag has already been used. Please select different one.
        '500':
          description: Something went wrong
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorData'
              example:
                responseData:
                  status: 500
                  message: Something went wrong.
      x-codegen-request-body-name: body
      operationId: postTagsEdit{id}Json
      x-operation-id-source: derived
  /tags/delete/{id}.json:
    delete:
      tags:
      - Tags
      summary: Delete a tag
      parameters:
      - name: id
        in: path
        description: Tag ID to delete
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: No error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessGeneralData'
              example:
                responseData:
                  status: 200
        '404':
          description: Tag not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorData'
              example:
                responseData:
                  status: 404
                  message: Not found.
      operationId: deleteTagsDelete{id}Json
      x-operation-id-source: derived
components:
  schemas:
    PaginationData:
      type: object
      properties:
        itemsCount:
          type: integer
          description: number of resources in the response
          format: int64
        pageCount:
          type: integer
          description: number of pages found
          format: int64
        pageNumber:
          type: integer
          description: current page in the response
          format: int64
        limit:
          type: integer
          description: number of objects sent per page
          format: int64
      description: Call data
    ErrorData:
      type: object
      properties:
        status:
          type: string
          description: Status code
        message:
          type: string
          description: The error message
    StatusCode:
      type: object
      properties:
        status:
          type: string
          description: Status code
    ErrorInvalidData:
      type: object
      properties:
        status:
          type: string
          description: Status code
        message:
          type: string
          description: The error message
        data:
          type: object
          properties: {}
          description: More data explaining the error
    SuccessGeneralData:
      type: object
      properties:
        status:
          type: string
          description: Status code
