openapi: 3.2.0
info:
  title: CloudTalk Utilities API
  description: '# Introduction

    Welcome to CloudTalk API reference! Many of these businesses use the CloudTalk API to automate and enhance their customer support with CloudTalk Support. With CloudTalk we are re-building telco industry from the ground and taking it to the next level with first-class customer support system. Please find below the full documenation to CloudTalk. # API Overview


    The API is organized around the following resources:


    API Area | Description

    ----------------|-------------

    Calls | Browse your call history, download recordings and access all your calls data. Contacts | Create and update Contacts. Use filters to get lists of Contacts, or access their profiles individually. Numbers | Automate Numbers modifications. List all your numbers. Agents | Create or update your Agents, access their settings. Conversation Intelligence | Get Conversation Intelligence data about your calls. VoiceAgent | Initiate VoiceAgent calls


    JSON is returned in all responses. XML is not supported. The API also uses common approaches for the following:


    Function | Description

    ----------------|-------------

    Data | API data is JSON encoded with UTF-8. API JSON is either a single object or a list of objects. Errors | 4xx and 5xx responses returning JSON with error codes

    Rate Limiting | Controls how many requests can be made in a time window

    HTTP | Methods are used in accordance with HTTP (GET POST and DELETE are the primary methods used) and resources are identified using URIs. All API requests are sent over HTTPS. ## Authentication


    This is an HTTPS-only API. Authentication is based on API Access Key ID and Access Key Secret. The API Access Key ID and Access Key Secret is passed via HTTP Basic Authentication. Basic Auth credentials are used to determine on which project should this request be executed on. List of all Basic Auth credentials for the project can be found by Administrators in the CloudTalk Dashboard under Account → Settings → API Keys (https://dashboard.cloudtalk.io/menu/account/settings/API-keys). To try the API via curl on the command-line, the general form used would be:

    ```

    curl -u ACCESS_KEY_ID:ACCESS_KEY_SECRET API_URL

    ```


    For instance, you would execute:

    ```

    curl -u ABCDEFGHIJTESTKEY1:X05Dg4c331c3h61An https://my.cloudtalk.io/api/calls/index.json

    ```


    ## Usage


    The API may rate limit submission of requests for your application. Such limits are managed as an allowed number of operations per time window, where an operation might be read or an update. In that case a **''429 Too Many Requests''** response code will be returned along with the following headers -


    Header name | Description

    ----------------|-------------

    X-CloudTalkAPI-Limit | Maximum number of API requests allowed in the current time window. X-CloudTalkAPI-Remaining | Number of API requests left in the current window. X-CloudTalkAPI-ResetTime | Time when rate limit window will be reset as a Unix timestamp. Note that the default rate limit is **60 operations per minute per company**. If you need to make more requests, please contact our support with detailed explanation of your use case. ## Response Envelopes


    **Note:** Conversation Intelligence doesn''t follow envelopes. The API returns one of three envelopes depending upon the request issued:


    1. Single Item Envelope

    2. Collections Envelope

    3. Error Envelope


    ### Single Item Envelope


    All dates/times are returned in ISO8601 format and in UTC timezone. ```

    Status: 200 OK

    {

    "responseData": {

    "id": 123,

    ... "created": "2018-01-10 12:34:56"

    }

    }

    ```


    ### Collections Envelope


    All dates/times are returned in ISO8601 format and in UTC timezone. ```

    Status: 200 OK

    {

    "responseData": {

    "itemsCount": 65,

    "pageCount": 3,

    "pageNumber": 1,

    "limit": 30,

    "data": [

    {

    "id": 123,

    ... "created": "2018-01-10 12:34:56"

    },

    {

    "id": 456,

    ... "created": "2017-10-19 09:21:29"

    },

    ...'
  contact:
    name: CloudTalk API Support
    url: https://www.cloudtalk.io/contact
  version: '1.7'
  x-logo:
    url: https://my.cloudtalk.io/img/logo-cloudtalk-color.png
servers:
- url: https://my.cloudtalk.io/api
security:
- basicAuth: []
tags:
- name: Utilities
  description: All other helper endpoints.
paths:
  /countries/index.json:
    get:
      tags:
      - Utilities
      summary: List countries
      description: Returns every country CloudTalk recognises, with the `country_id` values used by the contact endpoints. Takes no parameters.
      responses:
        '200':
          description: All countries
          content:
            application/json:
              schema:
                type: object
                properties:
                  responseData:
                    type: array
                    items:
                      type: object
                      properties:
                        Country:
                          $ref: '#/components/schemas/Country'
              example:
                responseData:
                - Country:
                    id: '61'
                    name: Denmark
                    country_code: DK
                    iso3: DNK
                    calling_code: '45'
                - Country:
                    id: '235'
                    name: United Kingdom
                    country_code: GB
                    iso3: GBR
                    calling_code: '44'
      operationId: getCountriesIndexJson
      x-operation-id-source: derived
  /blacklist/index.json:
    get:
      tags:
      - Utilities
      summary: List blacklist
      description: List blacklisted numbers.
      parameters:
      - name: id
        in: query
        description: Filter by ID
        schema:
          type: integer
      - name: country_code
        in: query
        description: Filter by country calling code
        schema:
          type: integer
      - name: type
        in: query
        description: Filter by type
        schema:
          type: string
          enum:
          - all
          - incoming
          - outgoing
      - name: public_number
        in: query
        description: Filter by number
        schema:
          type: string
      - name: limit
        in: query
        description: Max. number of items in response data.
        schema:
          maximum: 1000
          minimum: 1
          type: integer
      - name: page
        in: query
        description: Number of page to return.
        schema:
          minimum: 1
          type: integer
      responses:
        '200':
          description: Blacklist data
          content:
            application/json:
              schema:
                type: object
                properties:
                  responseData:
                    type: object
                    properties:
                      itemsCount:
                        type: integer
                        description: number of resources in the response
                        format: int64
                      pageCount:
                        type: integer
                        description: number of pages found
                        format: int64
                      pageNumber:
                        type: integer
                        description: current page in the response
                        format: int64
                      limit:
                        type: integer
                        description: number of objects sent per page
                        format: int64
                      data:
                        type: array
                        items:
                          type: object
                          properties:
                            Blacklist:
                              $ref: '#/components/schemas/Blacklist'
                required:
                - responseData
              example:
                responseData:
                  itemsCount: 2
                  pageCount: 1
                  pageNumber: 1
                  limit: 2
                  data:
                  - Blacklist:
                      id: '123'
                      type: all
                      public_number: 442012345678
                  - Blacklist:
                      id: '456'
                      type: incoming
                      public_number: 442012345679
      operationId: getBlacklistIndexJson
      x-operation-id-source: derived
  /blacklist/add.json:
    put:
      tags:
      - Utilities
      summary: Add number to blacklist
      description: Add number to blacklist.
      requestBody:
        content:
          application/json:
            schema:
              required:
              - public_number
              - type
              type: object
              properties:
                type:
                  type: string
                  description: Type of calls
                  enum:
                  - all
                  - incoming
                  - outgoing
                public_number:
                  type: string
                  description: Blacklisted number in E.164 format
        required: true
      responses:
        '201':
          description: No error
          content:
            application/json:
              schema:
                type: object
                properties:
                  responseData:
                    type: object
                    properties:
                      status:
                        type: integer
                        description: Status code
                      data:
                        type: object
                        properties:
                          id:
                            type: integer
                            description: Blacklist ID
                required:
                - responseData
              example:
                responseData:
                  status: 201
                  data:
                    id: '12345'
        '406':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorInvalidData'
              example:
                responseData:
                  status: 406
                  message: Invalid input data.
                  data:
                    public_number:
                    - Please supply only valid numbers. Number +441234 is not valid.
        '500':
          description: Something went wrong
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorData'
              example:
                responseData:
                  status: 500
                  message: Something went wrong.
      x-codegen-request-body-name: body
      operationId: putBlacklistAddJson
      x-operation-id-source: derived
  /blacklist/edit/{id}.json:
    post:
      tags:
      - Utilities
      summary: Edit number on blacklist
      description: Edit blacklisted number.
      parameters:
      - name: id
        in: path
        description: ID to edit
        required: true
        schema:
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              required:
              - public_number
              - type
              type: object
              properties:
                type:
                  type: string
                  description: Type of calls
                  enum:
                  - all
                  - incoming
                  - outgoing
                public_number:
                  type: string
                  description: Blacklisted number in E.164 format
        required: true
      responses:
        '200':
          description: No error
          content:
            application/json:
              schema:
                type: object
                properties:
                  responseData:
                    type: object
                    properties:
                      status:
                        type: integer
                        description: Status code
                required:
                - responseData
              example:
                responseData:
                  status: 200
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorData'
              example:
                responseData:
                  status: 404
                  message: Not found.
        '406':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorInvalidData'
              example:
                responseData:
                  status: 406
                  message: Invalid input data.
                  data:
                    public_number:
                    - Please supply only valid numbers. Number +441234 is not valid.
        '500':
          description: Something went wrong
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorData'
              example:
                responseData:
                  status: 500
                  message: Something went wrong.
      x-codegen-request-body-name: body
      operationId: postBlacklistEdit{id}Json
      x-operation-id-source: derived
  /blacklist/delete/{id}.json:
    delete:
      tags:
      - Utilities
      summary: Delete number from blacklist
      description: Delete the number from blacklist.
      parameters:
      - name: id
        in: path
        description: ID to delete
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: No error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessGeneralData'
              example:
                responseData:
                  status: 200
        '404':
          description: Blacklist not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorData'
              example:
                responseData:
                  status: 404
                  message: Not found.
        '500':
          description: Something went wrong
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorData'
              example:
                responseData:
                  status: 500
                  message: Something went wrong.
      operationId: deleteBlacklistDelete{id}Json
      x-operation-id-source: derived
components:
  schemas:
    Country:
      type: object
      properties:
        id:
          type: integer
          description: Country ID
        name:
          type: string
          description: Name
        country_code:
          type: string
          description: Country code by ISO_3166-1 Alpha-2
        iso3:
          type: string
          description: Country code by ISO_3166-1 Alpha-3
        calling_code:
          type: string
          description: Country calling code
      description: Country data
    SuccessGeneralData:
      type: object
      description: Success envelope returned by the core API on `my.cloudtalk.io/api`. The payload is always wrapped in `responseData`.
      properties:
        responseData:
          type: object
          properties:
            status:
              type: integer
              description: Status code
      required:
      - responseData
    ErrorInvalidData:
      type: object
      description: Validation-error envelope returned by the core API on `my.cloudtalk.io/api`. The payload is always wrapped in `responseData`.
      properties:
        responseData:
          type: object
          properties:
            status:
              type: integer
              description: HTTP status code
            message:
              type: string
              description: The error message
            data:
              type: object
              properties: {}
              description: Field-level detail explaining the error
          required:
          - status
          - message
      required:
      - responseData
    Blacklist:
      type: object
      properties:
        id:
          type: integer
          description: Blacklist ID
        type:
          type: string
          description: Type of calls
          enum:
          - all
          - incoming
          - outgoing
        public_number:
          type: string
          description: Blacklisted number in E.164 format
        created:
          type: string
          description: Created date and time
          format: date-time
        modified:
          type: string
          description: Last modified date and time
          format: date-time
      description: Blacklist data
    ErrorData:
      type: object
      description: Error envelope returned by the core API on `my.cloudtalk.io/api`. The payload is always wrapped in `responseData`.
      properties:
        responseData:
          type: object
          properties:
            status:
              type: integer
              description: HTTP status code
            message:
              type: string
              description: The error message
          required:
          - status
          - message
      required:
      - responseData
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
      description: HTTP Basic Authentication. Use your API Access Key ID as the username and your API Access Key Secret as the password. Generate keys in the CloudTalk Dashboard under Account -> Settings -> API Keys (https://dashboard.cloudtalk.io/menu/account/settings/API-keys).
